### ISSUE TITLE
iOS10 coming ?

### ISSUE THREAD

**Issue by NielsG** [saffad/iOS-Text-Styles-in-Sketch#1]
Are you planning on updating this to the new iOS 10 styles? Here's the 'new' list: https://developer.apple.com/ios/human-interface-guidelines/visual-design/typography/

**Comment by saffad** [comment]
@NielsG Nice one. Expect an update from me soon...

**Comment by saffad** [comment]
I've cross checked my text styles with iOS 10 and good news is that nothing has changed. I updated the README to include the link to the new iOS HIG.

**Comment by FeedyFeedback** [comment]
@NielsG Is your github account / github username for sale? I would like to use it, if possible!
