### ISSUE TITLE
Inclusive app design support [JP]

### ISSUE THREAD

**Issue by riomarmccartney** [saffad/iOS-Text-Styles-in-Sketch#2]
# Inclusive App Design

![screen shot 2016-07-06 at 11 36 08](https://cloud.githubusercontent.com/assets/3750705/16605885/1dfd8e3a-436e-11e6-9d61-b64bd13a7293.png)

This was a hot topic at WWDC because iOS is now all around the world and it is used by many different people with different cultures. So designing and considering only alphabetical format is becoming a thing of the past, we as designer must consider about other languages and make it accessible to people not native to alphabets. 

Your sketch was super helpful to simulate System Font used in Xcode. It's clearly a great idea to make it into a styled text format for Sketch. So I thought, why not make it inclusive, so that designers that are making for other international markets don't have to research all over again about how typography will be treated in different languages and regions. 

Right now I mainly work for the Japanese market, and as you can see on the table above (2nd Column), Japanese System Font (Hiragino Sans) have only **2 weights**. Plus Japanese fonts are generally larger than the alphabet we know, font size do change when styling, but in Xcode It's considered the same. 
For example, Body style in alphabet is SF Text Regular 17pt, whereas the same style in Japanese would be Hiragino Sans W3 16pt. 

This is a real pain and confusion when making typographic layouts for both languages, so following your sketch file format, I made a Japanese version (screenshot below). I would love to contribute to this repo so that the resources are all together for designers around the world. @saffad 

![screen shot 2016-07-06 at 11 28 37](https://cloud.githubusercontent.com/assets/3750705/16606169/a1a80538-4370-11e6-8eb5-19a15627ac81.png)

PS : I tried to be as perfect as possible, replicating the System Font in Japanese but there are some limits to Sketch and by the way OS X treats Japanese font. The red text layout is sketch, the background is the text generated from Xcode System Font. 

<img width="2672" alt="screen shot 2016-07-05 at 9 42 48 pm" src="https://cloud.githubusercontent.com/assets/3750705/16606218/09107480-4371-11e6-984b-82048454c630.png">

**Comment by saffad** [comment]
This is amazing @Riotherio. I'm trying to think of the best way to include your work. What about a sketch file with 2 pages:
1. Latin
2. Japanese

What do you think? Feel free to make a Pull Request with the updated file 👍

**Comment by riomarmccartney** [comment]
Thank you @saffad! 

> What about a sketch file with 2 pages: 
> 1. Latin
> 2. Japanese

Seems good to me! I'll pull request right away!
